name: Jest Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Puedes ajustar la versión de Node.js según tu proyecto

      - name: Install Dependencies
        run: npm install # Aquí puedes usar 'yarn install' si estás utilizando Yarn

      - name: Run Jest Tests
        run: npm test # Aquí puedes usar 'yarn test' si estás utilizando Yarn
